name: jambo_app
description: A new Flutter project for Jambo VoIP app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  sqflite_common_ffi_web: ^0.4.5+3
  path: ^1.8.0
  animations: ^2.0.3
  provider: ^6.0.3
  flutter_neumorphic: ^3.2.0
  fluttertoast: ^8.0.9
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  sqlite3_flutter_libs: ^0.5.0
  web_socket_channel: ^3.0.1
  awesome_notifications: ^0.10.0
  flutter_sound: ^9.2.13
  vibration: ^2.0.1
  flutter_contacts: ^1.1.7+1
  connectivity_plus: ^6.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  just_audio: ^0.9.34
  fl_chart: ^0.69.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  audio_session: ^0.1.16
  flutter_ringtone_player: ^4.0.0+3
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  url_launcher: ^6.1.14
  share_plus: ^10.1.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_slidable: ^3.0.0
  rxdart: ^0.28.0
  http: ^1.1.0
  flutter_webrtc: ^0.12.1+hotfix.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

# Noter que nous ne spécifions que les dossiers assets que nous utilisons réellement
  assets:
    - assets/sounds/
    - assets/images/
    - assets/icons/

# Nous retirons complètement la section fonts car nous n'avons pas les fichiers de police

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true